### ISSUE TITLE
Problem with removing dangling multi-arch container manifests from Azure Container Registry

### ISSUE THREAD

**Issue by Wesztman** [neumanndaniel/kubernetes#6]
Hi Daniel! 

First of I want to express a huge thanks to you for your work in this repo, its invaluable! So thanks for that!

I'm trying to run the following script in an azure devops pipeline

https://github.com/neumanndaniel/kubernetes/blob/master/acr/Remove-UntaggedManifestsDockerBuildx.ps1

But when I get to a multi-architecture repo I get 

![image](https://github.com/neumanndaniel/kubernetes/assets/54413402/b34c37f6-40ab-4c3f-9837-c8dc499c249d)

Does this have to do with the line 

`$HEADERS = @{ 'accept' = 'application/vnd.docker.distribution.manifest.v2+json' }` ?

Since the image is marked as,

![image](https://github.com/neumanndaniel/kubernetes/assets/54413402/e94e3bad-4190-47f6-8efd-5e4594491b10)

Do you have any safe fix for this? :) 

Cheers 
Carl

**Comment by Wesztman** [comment]
Would it be safe to just do? 🤔

`$HEADERS = @{ 'accept' = 'application/vnd.docker.distribution.manifest.v2+json, application/vnd.oci.image.index.v1+json' }`

**Comment by Wesztman** [comment]
The v2 media type does not seem to have any `manifests` section 🤔 so it might have to accept the oci v1 media type to even work correctly?

![image](https://github.com/neumanndaniel/kubernetes/assets/54413402/7383c5db-0cdb-42c9-8e1a-0bc977d5856c)

**Comment by neumanndaniel** [comment]
Hi @Wesztman,

sorry for the late reply. I need to check my GitHub notifications more frequently. :D

I assume you already have verified the adjustment you proposed in your PR, if that is correct I am happy to accept the PR and merge it.

Thanks,
Daniel

**Comment by Wesztman** [comment]
Hi @neumanndaniel 😊 no problems! This is verified and working as intended 👍

**Comment by neumanndaniel** [comment]
Thanks for the contribution I merged the PR. 🙂
